version: '3.8'

services:
  db:
    image: postgres:16-bookworm
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: njm
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["npm", "run", "dev"]
    restart: always
    environment:
      NODE_PORT: 8000
      DATABASE_HOST: db:5432
      DATABASE_NAME: njm
      DATABASE_USER: admin
      DATABASE_PASS: password
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

volumes:
  db-data:
