name: njm server build
run-name: ${{ github.actor }} - ${{ github.event_name }} - ${{ github.sha }}

on: 
  push: 
    branches:
      - main
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: njm-server

jobs:
  create-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: ghcr login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.run_id }}